name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: run-vcpkg
      if: matrix.os == 'windows.latest'
      uses: lukka/run-vcpkg@v0.10
      with:
        vcpkgArguments: 'zlib'
    - name: configure (windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: mkdir build && cd build && cmake ..
    - name: configure
      if: matrix.os != 'windows-latest'
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
